// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.6.1
// source: typed.proto

package typed

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Annotation associates a type with a blob reference.
// The annotated blob is a serialized protobuf.
// The type is itself a blob reference.
// The type's blob is the serialized descriptor of the annotated blob's protobuf.
type Annotation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ref []byte `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Typ []byte `protobuf:"bytes,2,opt,name=typ,proto3" json:"typ,omitempty"`
}

func (x *Annotation) Reset() {
	*x = Annotation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_typed_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Annotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Annotation) ProtoMessage() {}

func (x *Annotation) ProtoReflect() protoreflect.Message {
	mi := &file_typed_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Annotation.ProtoReflect.Descriptor instead.
func (*Annotation) Descriptor() ([]byte, []int) {
	return file_typed_proto_rawDescGZIP(), []int{0}
}

func (x *Annotation) GetRef() []byte {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *Annotation) GetTyp() []byte {
	if x != nil {
		return x.Typ
	}
	return nil
}

var File_typed_proto protoreflect.FileDescriptor

var file_typed_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x79, 0x70, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74,
	0x79, 0x70, 0x65, 0x64, 0x22, 0x30, 0x0a, 0x0a, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x03, 0x72, 0x65, 0x66, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x79, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x03, 0x74, 0x79, 0x70, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x74, 0x79, 0x70, 0x65,
	0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_typed_proto_rawDescOnce sync.Once
	file_typed_proto_rawDescData = file_typed_proto_rawDesc
)

func file_typed_proto_rawDescGZIP() []byte {
	file_typed_proto_rawDescOnce.Do(func() {
		file_typed_proto_rawDescData = protoimpl.X.CompressGZIP(file_typed_proto_rawDescData)
	})
	return file_typed_proto_rawDescData
}

var file_typed_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_typed_proto_goTypes = []interface{}{
	(*Annotation)(nil), // 0: typed.Annotation
}
var file_typed_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_typed_proto_init() }
func file_typed_proto_init() {
	if File_typed_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_typed_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Annotation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_typed_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_typed_proto_goTypes,
		DependencyIndexes: file_typed_proto_depIdxs,
		MessageInfos:      file_typed_proto_msgTypes,
	}.Build()
	File_typed_proto = out.File
	file_typed_proto_rawDesc = nil
	file_typed_proto_goTypes = nil
	file_typed_proto_depIdxs = nil
}
