// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: split.proto

package split

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Node is a node in a hashsplit tree created with split.Write.
type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Offsets and refs of other Nodes.
	Nodes []*Child `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	// Offsets and refs of leaf blobs.
	Leaves []*Child `protobuf:"bytes,2,rep,name=leaves,proto3" json:"leaves,omitempty"`
	// Offset in the input stream of the beginning of the bytes represented by this child.
	Offset uint64 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	// Number of bytes represented by this node.
	Size uint64 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *Node) Reset() {
	*x = Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_split_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_split_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_split_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetNodes() []*Child {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Node) GetLeaves() []*Child {
	if x != nil {
		return x.Leaves
	}
	return nil
}

func (x *Node) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Node) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type Child struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Ref of child (node or blob).
	Ref []byte `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	// Offset of this child (duplicates Node.off).
	Offset uint64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *Child) Reset() {
	*x = Child{}
	if protoimpl.UnsafeEnabled {
		mi := &file_split_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Child) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Child) ProtoMessage() {}

func (x *Child) ProtoReflect() protoreflect.Message {
	mi := &file_split_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Child.ProtoReflect.Descriptor instead.
func (*Child) Descriptor() ([]byte, []int) {
	return file_split_proto_rawDescGZIP(), []int{1}
}

func (x *Child) GetRef() []byte {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *Child) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_split_proto protoreflect.FileDescriptor

var file_split_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x70, 0x6c, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73,
	0x70, 0x6c, 0x69, 0x74, 0x22, 0x7c, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x22, 0x0a, 0x05,
	0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x70,
	0x6c, 0x69, 0x74, 0x2e, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73,
	0x12, 0x24, 0x0a, 0x06, 0x6c, 0x65, 0x61, 0x76, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x73, 0x70, 0x6c, 0x69, 0x74, 0x2e, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x52, 0x06,
	0x6c, 0x65, 0x61, 0x76, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x22, 0x31, 0x0a, 0x05, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x72,
	0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x72, 0x65, 0x66, 0x12, 0x16, 0x0a,
	0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x73, 0x70, 0x6c, 0x69, 0x74,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_split_proto_rawDescOnce sync.Once
	file_split_proto_rawDescData = file_split_proto_rawDesc
)

func file_split_proto_rawDescGZIP() []byte {
	file_split_proto_rawDescOnce.Do(func() {
		file_split_proto_rawDescData = protoimpl.X.CompressGZIP(file_split_proto_rawDescData)
	})
	return file_split_proto_rawDescData
}

var file_split_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_split_proto_goTypes = []interface{}{
	(*Node)(nil),  // 0: split.Node
	(*Child)(nil), // 1: split.Child
}
var file_split_proto_depIdxs = []int32{
	1, // 0: split.Node.nodes:type_name -> split.Child
	1, // 1: split.Node.leaves:type_name -> split.Child
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_split_proto_init() }
func file_split_proto_init() {
	if File_split_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_split_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_split_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Child); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_split_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_split_proto_goTypes,
		DependencyIndexes: file_split_proto_depIdxs,
		MessageInfos:      file_split_proto_msgTypes,
	}.Build()
	File_split_proto = out.File
	file_split_proto_rawDesc = nil
	file_split_proto_goTypes = nil
	file_split_proto_depIdxs = nil
}
